/**
 * 相册列表页（Phase 3b）。
 *
 * 数据来源：TanStack Query，通过 `useSuspenseQuery` 从
 * `photoAlbumsListQueryOptions(...)` 读取。路由 loader 已通过
 * `context.queryClient.query({ ...options, staleTime: 'static' })`
 * 预热缓存，本组件不再读 `useLoaderData` / `HttpClient`。
 *
 * 乐观更新：创建 / 编辑 / 删除全部走 `../hooks/use-albums`，由 hook
 * 写入 Query 缓存并在失败时回滚到快照。页面只保留表单接线与路由跳转，
 * 不再维护数组状态——loader 以 `staleTime: 'static'` 预热，只写本地
 * 状态的变更会在下次挂载时丢失。
 */

import { ZButton, ZGrid } from '@zcat/ui';
import React from 'react';
import { useNavigate } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import zod from 'zod';

import {
  AlbumImageCard,
  type PhotoAlbumData,
} from '@cms/features/album/components/album';
import {
  createCheckbox,
  createConstNumber,
  createInput,
  createSchemaForm,
  createTextArea,
  PaginationWorkspace,
} from '@cms/core';
import { photoAlbumsListQueryOptions } from '@cms/server/albums';
import type {
  GetPhotoAlbumsInput,
  PaginatedPhotoAlbums,
  PhotoAlbum,
} from '@cms/server/albums/schemas';

import {
  type AlbumFormValues,
  useCreateAlbum,
  useDeleteAlbum,
  useUpdateAlbum,
} from '../hooks/use-albums';

interface AlbumsListProps {
  search: Record<string, unknown>;
}

/**
 * 相册页面
 * @returns
 */
export default function Albums({ search }: AlbumsListProps) {
  const navigate = useNavigate();
  const { page, pageSize } = deriveAlbumListQueryArgs(search);
  const { data: pagination } = useSuspenseQuery(
    photoAlbumsListQueryOptions({ page, pageSize }),
  );
  // The `queryFn` in `photoAlbumsListQueryOptions` is a closure over
  // a TanStack Start server function, which TypeScript cannot infer
  // through. The shape is fixed by the corresponding Zod schema
  // (`PaginatedPhotoAlbumsSchema`) so we narrow here.
  const paginated = pagination as unknown as PaginatedPhotoAlbums;
  // 变更期间缓存里带 `loading: true` 的行就是乐观更新的行，
  // 所以列表直接渲染缓存即可。
  const albums = paginated.data as PhotoAlbumData[];

  const createAlbum = useCreateAlbum({ page, pageSize });
  const updateAlbum = useUpdateAlbum();
  const deleteAlbum = useDeleteAlbum({ page, pageSize });

  const deleteItem = (item: PhotoAlbumData) => {
    React.startTransition(async () => {
      try {
        await deleteAlbum.mutateAsync(item.id);
      } catch {
        // 快照已由 hook 回滚
      }
    });
  };

  const create = useAlbumForm({
    title: '新增相册',
    onSubmit: async (data: AlbumFormValues) => {
      React.startTransition(async () => {
        try {
          await createAlbum.mutateAsync({
            name: data.name,
            description: data.description,
            available: data.available,
          });
        } catch {
          // 快照已由 hook 回滚
        }
      });
    },
  });

  const edit = useAlbumForm({
    title: '编辑相册',
    confirmText: '保存',
    onSubmit: async (data: AlbumFormValues) => {
      React.startTransition(async () => {
        try {
          await updateAlbum.mutateAsync(data);
        } catch {
          // 快照已由 hook 回滚
        }
      });
    },
  });

  const handleClickAlbum = React.useCallback(
    (item: PhotoAlbum) => {
      // The detail route is mounted at `/_cms/albums/$albumId`;
      // route id is `/albums/$albumId` under the pathless `_cms`
      // layout. The route tree is regenerated by the Vite plugin
      // at dev/build time; we cast loosely so this file compiles
      // even when the tree is stale.
      navigate({
        to: '/albums/$albumId' as never,
        params: { albumId: String(item.id) } as never,
      });
    },
    [navigate],
  );

  return (
    <PaginationWorkspace
      title="相册列表"
      operation={
        <ZButton
          onClick={() => {
            create({
              id: 0,
              name: '默认相册',
              available: false,
              description: '',
            });
          }}
        >
          新增相册
        </ZButton>
      }
      pageSize={paginated.pageSize}
      totalPages={paginated.totalPages}
      page={paginated.page}
    >
      <ZGrid
        items={albums}
        cols={3}
        columnClassName="px-0"
        renderItem={(item) => (
          <AlbumImageCard
            // `AlbumImageCard` was built against the legacy
            // `AlbumsApi.PhotoAlbum` shape (`cover?: Photo`). The
            // server surface now returns `cover?: Photo | null`; we
            // narrow `null` to `undefined` so the legacy component
            // contract stays intact.
            data={{
              ...item,
              cover: item.cover
                ? {
                    id: item.cover.id,
                    name: item.cover.name,
                    url: item.cover.url,
                    thumbnailUrl: item.cover.thumbnailUrl,
                    albumId: item.cover.albumId ?? undefined,
                    isCover: item.cover.isCover,
                    createdAt: item.cover.createdAt,
                    updatedAt: item.cover.updatedAt,
                  }
                : undefined,
            }}
            onClickItem={handleClickAlbum}
            onEdit={edit}
            onDelete={deleteItem}
          />
        )}
      />
    </PaginationWorkspace>
  );
}

/**
 * 从路由传入的 search 参数中派生 Query key，使页面 key 与路由
 * loader 预热的 key 保持一致。loader 已经用同样的参数调用了
 * `query({ ...options, staleTime: 'static' })`，因此 SSR 首次渲染命中缓存。
 */
function deriveAlbumListQueryArgs(
  search: Record<string, unknown>,
): Pick<GetPhotoAlbumsInput, 'page' | 'pageSize'> {
  return {
    page: coerceQueryNumber(search.page, 1),
    pageSize: coerceQueryNumber(search.pageSize, 10),
  };
}

function coerceQueryNumber(raw: unknown, defaultValue: number): number {
  if (raw == null || raw === '') {
    return defaultValue;
  }
  const parsed = Number(raw);
  return Number.isNaN(parsed) ? defaultValue : parsed;
}

// 相册创建表单
const useAlbumForm = createSchemaForm({
  fields: {
    id: createConstNumber(),
    name: createInput('相册名称'),
    description: createTextArea('相册描述'),
    available: createCheckbox('发布相册'),
  },
  schema: zod.object({
    id: zod.number().int().default(0),
    name: zod.string().min(1, '相册名称不能为空').default(''),
    description: zod.string().default(''),
    available: zod.boolean().default(false),
  }),
});
