-- CreateTable
CREATE TABLE `system_setting` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `ossConfig` TEXT NOT NULL,
    `userId` INTEGER NULL,
    `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    UNIQUE INDEX `REL_3a7fa0c3809d19eaf2fb4f6594`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
