FROM node:24.12.0-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack install --global pnpm@latest
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

FROM base AS build
ENV HUSKY=0
ENV DATABASE_URL=postgresql://build:build@localhost:5432/build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm --filter=backend install --frozen-lockfile
RUN pnpm --filter=backend run build
RUN pnpm deploy --filter=backend --prod --legacy /prod/backend

FROM base AS backend
COPY --from=build /prod/backend /prod/backend
COPY --from=build /usr/src/app/apps/backend/dist /prod/backend/dist
WORKDIR /prod/backend
EXPOSE 9090
CMD [ "sh", "-c", "./node_modules/.bin/prisma migrate deploy && node dist/src/main.js" ]
