packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@prisma/engines': true
  '@swc/core': false
  bcrypt: false
  core-js: false
  cpu-features: false
  esbuild: false
  prisma: false
  ssh2: false

# injectWorkspacePackages: true
# syncInjectedDepsAfterScripts:
#   - build
#   - dist

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js
  - esbuild
  - prisma
  - unrs-resolver
