packages:
  - 'packages/*'
  - 'apps/*'

# injectWorkspacePackages: true
# syncInjectedDepsAfterScripts:
#   - build
#   - dist


ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js
  - esbuild
  - prisma
  - unrs-resolver
