/**
 * Thin route wrapper for `/albums` — the pathless `_cms` layout
 * supplies the auth guard and the Query client.
 *
 * The loader prefetches the paginated albums Query via
 * `context.queryClient.query({ ...photoAlbumsListQueryOptions(...), staleTime: 'static' })`
 * so the page can `useSuspenseQuery` from a warm cache slot. The
 * page itself reads from Query, not from `useLoaderData` /
 * `HttpClient` — that is the Phase 3b boundary.
 *
 * `page` / `pageSize` come from the router's parsed search object
 * (`location.search`). Defaults mirror the legacy list page
 * (1 / 10). We do NOT mutate the search params from the loader —
 * pagination is owned by the `PaginationWorkspace` upstream.
 *
 * The loader is exported as a top-level function so it is
 * unit-testable in isolation. `createFileRoute` accepts the same
 * reference as `Route.options.loader`, so the TanStack Router
 * integration still runs it on every navigation.
 *
 * NOTE: the typed `Route.LoaderArgs` is generated by the router
 * build plugin into `routeTree.gen.ts`. We type the loader
 * locally against the public `location.search` /
 * `context.queryClient` shape so typecheck stays green even
 * before the build runs.
 */

import { createFileRoute } from '@tanstack/react-router';
import type { QueryClient } from '@tanstack/react-query';

import Albums from '@cms/features/album/routes/albums';
import { photoAlbumsListQueryOptions } from '@cms/server/albums';

interface AlbumsListLoaderArgs {
  search: Record<string, unknown>;
  context: { queryClient: QueryClient };
}

/**
 * Coerce a raw search-param value to a positive integer, or
 * `defaultValue` when the value is missing / non-numeric. We do
 * NOT use `safeNumber` directly because it returns `NaN` for
 * `null` input (and `typeof NaN === 'number'`), which then trips
 * the `photoAlbumsListQueryOptions` Zod schema. Passing
 * `undefined` lets the schema's `.default(...)` and `.optional()`
 * chain resolve cleanly to the documented defaults.
 */
function coerceQueryInt(
  raw: unknown,
  defaultValue: number,
): number | undefined {
  if (raw == null) {
    return defaultValue;
  }
  const parsed = Number.parseInt(String(raw), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return defaultValue;
  }
  return parsed;
}

export async function loader({ search, context }: AlbumsListLoaderArgs) {
  const page = coerceQueryInt(search.page, 1) ?? 1;
  const pageSize = coerceQueryInt(search.pageSize, 10) ?? 10;

  return context.queryClient.query({
    ...photoAlbumsListQueryOptions({ page, pageSize }),
    staleTime: 'static',
  });
}

export const Route = createFileRoute('/_cms/albums')({
  loader: ({ context, location }) =>
    loader({ search: location.search, context }),
  component: AlbumsListRoute,
});

function AlbumsListRoute() {
  const search = Route.useSearch() as Record<string, unknown>;
  return <Albums search={search} />;
}
