/**
 * Thin route wrapper for `/albums` — the pathless `_cms` layout
 * supplies the auth guard and the Query client.
 *
 * The loader prefetches the paginated albums Query via
 * `context.queryClient.query({ ...photoAlbumsListQueryOptions(...), staleTime: 'static' })`
 * so the page can `useSuspenseQuery` from a warm cache slot. The
 * page itself reads from Query, not from `useLoaderData` /
 * `HttpClient` — that is the Phase 3b boundary.
 *
 * `page` / `pageSize` come from the router's parsed search object
 * (`location.search`). Defaults mirror the legacy list page
 * (1 / 10). We do NOT mutate the search params from the loader —
 * pagination is owned by the `PaginationWorkspace` upstream.
 *
 * The loader is exported as a top-level function so it is
 * unit-testable in isolation. `createFileRoute` accepts the same
 * reference as `Route.options.loader`, so the TanStack Router
 * integration still runs it on every navigation.
 *
 * NOTE: the typed `Route.LoaderArgs` is generated by the router
 * build plugin into `routeTree.gen.ts`. We type the loader
 * locally against the public `location.search` /
 * `context.queryClient` shape so typecheck stays green even
 * before the build runs.
 */

import { createFileRoute } from '@tanstack/react-router';
import type { QueryClient } from '@tanstack/react-query';

import Albums from '@cms/features/album/routes/albums';
import { paginationSearchSchema } from '@cms/shared/hooks/use-pagination-action';
import type { PaginationSearch } from '@cms/shared/hooks/use-pagination-action';
import { photoAlbumsListQueryOptions } from '@cms/server/albums';

interface AlbumsListLoaderArgs {
  search: PaginationSearch;
  context: { queryClient: QueryClient };
}

/**
 * `search` is already validated by `paginationSearchSchema`, so
 * `page` / `pageSize` arrive as positive integers or `undefined`.
 * The documented 1 / 10 defaults therefore live here rather than in
 * the shared schema, which `/photos` needs to differ on.
 */
export async function loader({ search, context }: AlbumsListLoaderArgs) {
  const page = search.page ?? 1;
  const pageSize = search.pageSize ?? 10;

  return context.queryClient.query({
    ...photoAlbumsListQueryOptions({ page, pageSize }),
    staleTime: 'static',
  });
}

export const Route = createFileRoute('/_cms/albums')({
  validateSearch: paginationSearchSchema,
  loader: ({ context, location }) =>
    loader({ search: location.search, context }),
  component: AlbumsListRoute,
});

function AlbumsListRoute() {
  const search = Route.useSearch();
  return <Albums search={search} />;
}
