/**
 * Thin route wrapper for `/albums/$albumId` — the pathless `_cms`
 * layout supplies the auth guard and the Query client.
 *
 * The loader prefetches THREE parallel Query slots via
 * `context.queryClient.query({ ...options, staleTime: 'static' })`
 * so the page can `useSuspenseQuery` from warm cache slots:
 *
 *   1. `photoAlbumDetailQueryOptions({ id })`  — the album record
 *   2. `photoListQueryOptions(...)`            — paginated photos
 *                                               scoped to this album
 *   3. `emptyAlbumPhotosQueryOptions()`        — the photo-selector
 *                                               source list
 *
 * `page` / `pageSize` come from the router's parsed search object
 * (`location.search`). Defaults mirror the legacy detail page
 * (1 / 20). An invalid `albumId` (non-numeric) throws so the
 * route's error boundary can take over without ever calling the
 * backend.
 *
 * The loader is exported as a top-level function so it is
 * unit-testable in isolation. `createFileRoute` accepts the same
 * reference as `Route.options.loader`, so the TanStack Router
 * integration still runs it on every navigation.
 *
 * NOTE: the typed `Route.LoaderArgs` is generated by the router
 * build plugin into `routeTree.gen.ts`. We type the loader
 * locally against the public `location.search` / `params` /
 * `context.queryClient` shape so typecheck stays green even
 * before the build runs.
 */

import { createFileRoute } from '@tanstack/react-router';
import type { QueryClient } from '@tanstack/react-query';

import { safeNumber } from '@zcat/ui';

import AlbumsId from '@cms/features/album/routes/albums.id';
import { photoAlbumDetailQueryOptions } from '@cms/server/albums';
import {
  emptyAlbumPhotosQueryOptions,
  photoListQueryOptions,
} from '@cms/server/photos';

interface AlbumDetailLoaderArgs {
  search: Record<string, unknown>;
  params: { albumId?: string };
  context: { queryClient: QueryClient };
}

/**
 * Coerce a raw search-param value to a positive integer, or
 * `defaultValue` when the value is missing / non-numeric. We do
 * NOT use `safeNumber` directly because it returns `NaN` for
 * `null` input (and `typeof NaN === 'number'`), which then trips
 * the downstream Zod schemas.
 */
function coerceQueryInt(
  raw: unknown,
  defaultValue: number,
): number | undefined {
  if (raw == null) {
    return defaultValue;
  }
  const parsed = Number.parseInt(String(raw), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return defaultValue;
  }
  return parsed;
}

export async function loader({
  search,
  params,
  context,
}: AlbumDetailLoaderArgs) {
  const page = coerceQueryInt(search.page, 1) ?? 1;
  const pageSize = coerceQueryInt(search.pageSize, 20) ?? 20;

  const albumId = safeNumber(params.albumId);
  if (Number.isNaN(albumId)) {
    throw new Error('Invalid album id');
  }

  return Promise.all([
    context.queryClient.query({
      ...photoAlbumDetailQueryOptions({ id: albumId }),
      staleTime: 'static',
    }),
    context.queryClient.query({
      ...photoListQueryOptions({ albumId, page, pageSize }),
      staleTime: 'static',
    }),
    context.queryClient.query({
      ...emptyAlbumPhotosQueryOptions(),
      staleTime: 'static',
    }),
  ]);
}

export const Route = createFileRoute('/_cms/albums_/$albumId')({
  loader: ({ context, location, params }) =>
    loader({ search: location.search, params, context }),
  component: AlbumDetailRoute,
});

function AlbumDetailRoute() {
  const { albumId } = Route.useParams() as { albumId: string };
  const search = Route.useSearch() as Record<string, unknown>;
  return <AlbumsId albumId={Number(albumId)} search={search} />;
}
