/**
 * Thin route wrapper for `/photos` — the pathless `_cms` layout
 * supplies the auth guard and the Query client.
 *
 * The loader prefetches the paginated photos Query via
 * `context.queryClient.query({ ...photoListQueryOptions(...), staleTime: 'static' })`
 * so the page can `useSuspenseQuery` from a warm cache slot. The
 * page itself reads from Query, not from `useLoaderData` /
 * `HttpClient` — that is the Phase 3b boundary.
 *
 * `page` / `pageSize` come from the URL search params. Defaults
 * mirror the legacy list page (1 / 20). An optional `albumId`
 * filter scopes the list to a single album; the page also exposes
 * an empty filter when none is set, so the cache slot is the
 * unfiltered photos list.
 *
 * Note: the loader warms the cache slot with
 * `queryClient.query({ ...photoListQueryOptions(...), staleTime: 'static' })`.
 * With `staleTime: 'static'`, the `query()` call returns the cached
 * value immediately if it already exists and never refetches while
 * the entry lives — the same "ensure the cache is warm for SSR /
 * navigation" semantics the deprecated
 * `QueryClient.ensureQueryData` used to provide.
 *
 * The loader is exported as a top-level `loader` function so the
 * route file's loader contract is unit-testable in isolation.
 * `createFileRoute` accepts the same reference as
 * `Route.options.loader`, so the TanStack Router integration
 * still runs it on every navigation.
 *
 * NOTE: the typed `Route.LoaderArgs` is generated by the router
 * build plugin into `routeTree.gen.ts`. We type the loader
 * locally against the public `location.search` /
 * `context.queryClient` shape so typecheck stays green even
 * before the build runs.
 */

import { createFileRoute } from '@tanstack/react-router';
import type { QueryClient } from '@tanstack/react-query';

import Photos from '@cms/features/photo/routes/photos';
import { photoListQueryOptions } from '@cms/server/photos';

interface PhotosLoaderArgs {
  search: Record<string, unknown>;
  context: { queryClient: QueryClient };
}

/**
 * Coerce a raw query-string value to a positive integer, or
 * `defaultValue` when the value is missing / non-numeric. We do
 * NOT use `safeNumber` directly because it returns `NaN` for
 * `null` input (and `typeof NaN === 'number'`), which then trips
 * the `photoListQueryOptions` Zod schema. Passing `undefined`
 * lets the schema's `.default(...)` and `.optional()` chain
 * resolve cleanly to the documented defaults.
 */
function coerceQueryInt(
  raw: unknown,
  defaultValue: number,
): number | undefined {
  if (raw == null) {
    return defaultValue;
  }
  const text = String(raw);
  if (text.length === 0) {
    return defaultValue;
  }
  const parsed = Number.parseInt(text, 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return defaultValue;
  }
  return parsed;
}

export async function loader({ search, context }: PhotosLoaderArgs) {
  const page = coerceQueryInt(search.page, 1) ?? 1;
  const pageSize = coerceQueryInt(search.pageSize, 20) ?? 20;
  const albumId = coerceQueryInt(search.albumId, 0);

  // Warm the cache slot with `QueryClient.query` +
  // `staleTime: 'static'` (the replacement for the deprecated
  // `QueryClient.ensureQueryData`). Spread the
  // `photoListQueryOptions(...)` result so the canonical query key +
  // queryFn + Zod-validated input are preserved, then override
  // `staleTime` so the cached entry never re-fetches while it lives —
  // same semantics as the legacy `ensureQueryData` call.
  return context.queryClient.query({
    ...photoListQueryOptions({
      albumId: albumId && albumId > 0 ? albumId : undefined,
      page,
      pageSize,
    }),
    staleTime: 'static',
  });
}

export const Route = createFileRoute('/_cms/photos')({
  loader: ({ context, location }) =>
    loader({ search: location.search as Record<string, unknown>, context }),
  component: Photos,
});
