/**
 * Thin route wrapper for `/photos` — the pathless `_cms` layout
 * supplies the auth guard and the Query client.
 *
 * The loader prefetches the paginated photos Query via
 * `context.queryClient.query({ ...photoListQueryOptions(...), staleTime: 'static' })`
 * so the page can `useSuspenseQuery` from a warm cache slot. The
 * page itself reads from Query, not from `useLoaderData` /
 * `HttpClient` — that is the Phase 3b boundary.
 *
 * `page` / `pageSize` come from the URL search params. Defaults
 * mirror the legacy list page (1 / 20). An optional `albumId`
 * filter scopes the list to a single album; the page also exposes
 * an empty filter when none is set, so the cache slot is the
 * unfiltered photos list.
 *
 * Note: the loader warms the cache slot with
 * `queryClient.query({ ...photoListQueryOptions(...), staleTime: 'static' })`.
 * With `staleTime: 'static'`, the `query()` call returns the cached
 * value immediately if it already exists and never refetches while
 * the entry lives — the same "ensure the cache is warm for SSR /
 * navigation" semantics the deprecated
 * `QueryClient.ensureQueryData` used to provide.
 *
 * The loader is exported as a top-level `loader` function so the
 * route file's loader contract is unit-testable in isolation.
 * `createFileRoute` accepts the same reference as
 * `Route.options.loader`, so the TanStack Router integration
 * still runs it on every navigation.
 *
 * NOTE: the typed `Route.LoaderArgs` is generated by the router
 * build plugin into `routeTree.gen.ts`. We type the loader
 * locally against the public `location.search` /
 * `context.queryClient` shape so typecheck stays green even
 * before the build runs.
 */

import { createFileRoute } from '@tanstack/react-router';
import type { QueryClient } from '@tanstack/react-query';

import Photos from '@cms/features/photo/routes/photos';
import { paginationSearchSchema } from '@cms/shared/hooks/use-pagination-action';
import type { PaginationSearch } from '@cms/shared/hooks/use-pagination-action';
import { photoListQueryOptions } from '@cms/server/photos';

interface PhotosLoaderArgs {
  search: PaginationSearch;
  context: { queryClient: QueryClient };
}

/**
 * `search` is already validated by `paginationSearchSchema`, so
 * `page` / `pageSize` / `albumId` arrive as positive integers or
 * `undefined` — a missing or non-positive `albumId` is simply
 * absent. The documented 1 / 20 defaults live here rather than in
 * the shared schema, which `/albums` and `/articles` differ on.
 */
export async function loader({ search, context }: PhotosLoaderArgs) {
  const page = search.page ?? 1;
  const pageSize = search.pageSize ?? 20;
  const albumId = search.albumId;

  // Warm the cache slot with `QueryClient.query` +
  // `staleTime: 'static'` (the replacement for the deprecated
  // `QueryClient.ensureQueryData`). Spread the
  // `photoListQueryOptions(...)` result so the canonical query key +
  // queryFn + Zod-validated input are preserved, then override
  // `staleTime` so the cached entry never re-fetches while it lives —
  // same semantics as the legacy `ensureQueryData` call.
  return context.queryClient.query({
    ...photoListQueryOptions({
      albumId,
      page,
      pageSize,
    }),
    staleTime: 'static',
  });
}

export const Route = createFileRoute('/_cms/photos')({
  validateSearch: paginationSearchSchema,
  loader: ({ context, location }) =>
    loader({ search: location.search, context }),
  component: Photos,
});
