/**
 * TanStack Start router entry.
 *
 * The routeTree is generated by the TanStack Router file-based
 * routing plugin from files in `./routes` (see vite.config.ts ->
 * tanstackStart().router).
 *
 * Phase 3a remediation: the Query SSR wiring is owned by the
 * official `@tanstack/react-router-ssr-query` integration. The
 * `getRouter()` factory builds a fresh `QueryClient` per call (the
 * browser and the SSR runtime each instantiate it once per request)
 * and hands it to the integration via
 * `setupRouterSsrQueryIntegration`. The integration then wires:
 *
 *   - `router.options.Wrap`         — wraps the router in a
 *     `QueryClientProvider` so any descendant can call
 *     `useQueryClient()`.
 *   - `router.options.dehydrate`    — captures the live query cache
 *     into the SSR dehydrated payload.
 *   - `router.options.hydrate`      — rehydrates the browser
 *     singleton on mount.
 *
 * We do NOT add a parallel `QueryClientProvider` /
 * `HydrationBoundary` in `__root.tsx` — that would conflict with
 * the integration-supplied `Wrap`. Per the integration docs:
 * "Do not add a second QueryClient or independently dehydrate the
 * same cache."
 *
 * The `context: { queryClient }` field is what makes the client
 * available inside `beforeLoad` / `loader` via
 * `context.queryClient`. The client is plain data on the context
 * slot; only the dehydrated router payload needs the QueryClient
 * instance, and the integration ferries that without serialising
 * the client itself.
 */

import { createRouter } from '@tanstack/react-router';
import { setupRouterSsrQueryIntegration } from '@tanstack/react-router-ssr-query';

import { makeQueryClient } from '@cms/shared/query';

import { routeTree } from './routeTree.gen';

export function getRouter() {
  // Build a fresh client per call. The SSR runtime calls
  // `getRouter()` once per request; the browser calls it once per
  // page load. A module-scope client would leak state across
  // requests.
  const queryClient = makeQueryClient();

  const router = createRouter({
    routeTree,
    context: { queryClient },
    scrollRestoration: true,
    // Per the official TanStack Start + Query guide: let Query
    // decide whether a preload needs data, and use a small
    // `staleTime` so the browser does not immediately re-read a
    // query right after SSR hydration.
    defaultPreload: 'intent',
    defaultPreloadStaleTime: 0,
  });

  // Official integration — call exactly once per router. We
  // disable `handleRedirects` because Phase 3a's `_cms.beforeLoad`
  // already throws redirects via `redirect(...)` and the router's
  // own redirect handling converts them into a navigation. The
  // Query cache's `onError` hook is unnecessary for a route guard
  // and has caused intermittent false redirects in the e2e suite.
  setupRouterSsrQueryIntegration({
    router,
    queryClient,
    handleRedirects: false,
  });

  return router;
}

export type Router = ReturnType<typeof getRouter>;
