/**
 * TanStack Start router entry.
 *
 * The routeTree is generated by the TanStack Router file-based routing plugin
 * from files in `./routes` (see vite.config.ts -> tanstackStart().router).
 */

import { createRouter } from '@tanstack/react-router';

import { routeTree } from './routeTree.gen';

export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
  });

  return router;
}

export type Router = ReturnType<typeof getRouter>;
