/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CmsRouteImport } from './routes/_cms';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CmsAlbumsRouteImport } from './routes/_cms/albums';
import { Route as CmsArticleCategoriesRouteImport } from './routes/_cms/article-categories';
import { Route as CmsArticlesRouteImport } from './routes/_cms/articles';
import { Route as CmsDashboardRouteImport } from './routes/_cms/dashboard';
import { Route as CmsPhotosRouteImport } from './routes/_cms/photos';
import { Route as CmsSettingsRouteImport } from './routes/_cms/settings';
import { Route as CmsUserInfoRouteImport } from './routes/_cms/user-info';
import { Route as CmsAlbumsAlbumIdRouteImport } from './routes/_cms/albums_.$albumId';
import { Route as CmsArticlesArticleIdRouteImport } from './routes/_cms/articles_.$articleId';
import { Route as CmsArticlesEditRouteImport } from './routes/_cms/articles_.edit';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const CmsRoute = CmsRouteImport.update({
  id: '/_cms',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const CmsAlbumsRoute = CmsAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => CmsRoute,
} as any);
const CmsArticleCategoriesRoute = CmsArticleCategoriesRouteImport.update({
  id: '/article-categories',
  path: '/article-categories',
  getParentRoute: () => CmsRoute,
} as any);
const CmsArticlesRoute = CmsArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => CmsRoute,
} as any);
const CmsDashboardRoute = CmsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CmsRoute,
} as any);
const CmsPhotosRoute = CmsPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => CmsRoute,
} as any);
const CmsSettingsRoute = CmsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CmsRoute,
} as any);
const CmsUserInfoRoute = CmsUserInfoRouteImport.update({
  id: '/user-info',
  path: '/user-info',
  getParentRoute: () => CmsRoute,
} as any);
const CmsAlbumsAlbumIdRoute = CmsAlbumsAlbumIdRouteImport.update({
  id: '/albums_/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => CmsRoute,
} as any);
const CmsArticlesArticleIdRoute = CmsArticlesArticleIdRouteImport.update({
  id: '/articles_/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => CmsRoute,
} as any);
const CmsArticlesEditRoute = CmsArticlesEditRouteImport.update({
  id: '/articles_/edit',
  path: '/articles/edit',
  getParentRoute: () => CmsRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/albums': typeof CmsAlbumsRoute;
  '/article-categories': typeof CmsArticleCategoriesRoute;
  '/articles': typeof CmsArticlesRoute;
  '/dashboard': typeof CmsDashboardRoute;
  '/photos': typeof CmsPhotosRoute;
  '/settings': typeof CmsSettingsRoute;
  '/user-info': typeof CmsUserInfoRoute;
  '/albums/$albumId': typeof CmsAlbumsAlbumIdRoute;
  '/articles/$articleId': typeof CmsArticlesArticleIdRoute;
  '/articles/edit': typeof CmsArticlesEditRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/albums': typeof CmsAlbumsRoute;
  '/article-categories': typeof CmsArticleCategoriesRoute;
  '/articles': typeof CmsArticlesRoute;
  '/dashboard': typeof CmsDashboardRoute;
  '/photos': typeof CmsPhotosRoute;
  '/settings': typeof CmsSettingsRoute;
  '/user-info': typeof CmsUserInfoRoute;
  '/albums/$albumId': typeof CmsAlbumsAlbumIdRoute;
  '/articles/$articleId': typeof CmsArticlesArticleIdRoute;
  '/articles/edit': typeof CmsArticlesEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_cms': typeof CmsRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_cms/albums': typeof CmsAlbumsRoute;
  '/_cms/article-categories': typeof CmsArticleCategoriesRoute;
  '/_cms/articles': typeof CmsArticlesRoute;
  '/_cms/dashboard': typeof CmsDashboardRoute;
  '/_cms/photos': typeof CmsPhotosRoute;
  '/_cms/settings': typeof CmsSettingsRoute;
  '/_cms/user-info': typeof CmsUserInfoRoute;
  '/_cms/albums_/$albumId': typeof CmsAlbumsAlbumIdRoute;
  '/_cms/articles_/$articleId': typeof CmsArticlesArticleIdRoute;
  '/_cms/articles_/edit': typeof CmsArticlesEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/albums'
    | '/article-categories'
    | '/articles'
    | '/dashboard'
    | '/photos'
    | '/settings'
    | '/user-info'
    | '/albums/$albumId'
    | '/articles/$articleId'
    | '/articles/edit';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/albums'
    | '/article-categories'
    | '/articles'
    | '/dashboard'
    | '/photos'
    | '/settings'
    | '/user-info'
    | '/albums/$albumId'
    | '/articles/$articleId'
    | '/articles/edit';
  id:
    | '__root__'
    | '/'
    | '/_cms'
    | '/login'
    | '/_cms/albums'
    | '/_cms/article-categories'
    | '/_cms/articles'
    | '/_cms/dashboard'
    | '/_cms/photos'
    | '/_cms/settings'
    | '/_cms/user-info'
    | '/_cms/albums_/$albumId'
    | '/_cms/articles_/$articleId'
    | '/_cms/articles_/edit';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CmsRoute: typeof CmsRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_cms': {
      id: '/_cms';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof CmsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_cms/albums': {
      id: '/_cms/albums';
      path: '/albums';
      fullPath: '/albums';
      preLoaderRoute: typeof CmsAlbumsRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/article-categories': {
      id: '/_cms/article-categories';
      path: '/article-categories';
      fullPath: '/article-categories';
      preLoaderRoute: typeof CmsArticleCategoriesRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/articles': {
      id: '/_cms/articles';
      path: '/articles';
      fullPath: '/articles';
      preLoaderRoute: typeof CmsArticlesRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/dashboard': {
      id: '/_cms/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof CmsDashboardRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/photos': {
      id: '/_cms/photos';
      path: '/photos';
      fullPath: '/photos';
      preLoaderRoute: typeof CmsPhotosRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/settings': {
      id: '/_cms/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof CmsSettingsRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/user-info': {
      id: '/_cms/user-info';
      path: '/user-info';
      fullPath: '/user-info';
      preLoaderRoute: typeof CmsUserInfoRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/albums_/$albumId': {
      id: '/_cms/albums_/$albumId';
      path: '/albums/$albumId';
      fullPath: '/albums/$albumId';
      preLoaderRoute: typeof CmsAlbumsAlbumIdRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/articles_/$articleId': {
      id: '/_cms/articles_/$articleId';
      path: '/articles/$articleId';
      fullPath: '/articles/$articleId';
      preLoaderRoute: typeof CmsArticlesArticleIdRouteImport;
      parentRoute: typeof CmsRoute;
    };
    '/_cms/articles_/edit': {
      id: '/_cms/articles_/edit';
      path: '/articles/edit';
      fullPath: '/articles/edit';
      preLoaderRoute: typeof CmsArticlesEditRouteImport;
      parentRoute: typeof CmsRoute;
    };
  }
}

interface CmsRouteChildren {
  CmsAlbumsRoute: typeof CmsAlbumsRoute;
  CmsArticleCategoriesRoute: typeof CmsArticleCategoriesRoute;
  CmsArticlesRoute: typeof CmsArticlesRoute;
  CmsDashboardRoute: typeof CmsDashboardRoute;
  CmsPhotosRoute: typeof CmsPhotosRoute;
  CmsSettingsRoute: typeof CmsSettingsRoute;
  CmsUserInfoRoute: typeof CmsUserInfoRoute;
  CmsAlbumsAlbumIdRoute: typeof CmsAlbumsAlbumIdRoute;
  CmsArticlesArticleIdRoute: typeof CmsArticlesArticleIdRoute;
  CmsArticlesEditRoute: typeof CmsArticlesEditRoute;
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsAlbumsRoute: CmsAlbumsRoute,
  CmsArticleCategoriesRoute: CmsArticleCategoriesRoute,
  CmsArticlesRoute: CmsArticlesRoute,
  CmsDashboardRoute: CmsDashboardRoute,
  CmsPhotosRoute: CmsPhotosRoute,
  CmsSettingsRoute: CmsSettingsRoute,
  CmsUserInfoRoute: CmsUserInfoRoute,
  CmsAlbumsAlbumIdRoute: CmsAlbumsAlbumIdRoute,
  CmsArticlesArticleIdRoute: CmsArticlesArticleIdRoute,
  CmsArticlesEditRoute: CmsArticlesEditRoute,
};

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRoute: CmsRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
